config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :invoices
  resources :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :invoices, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :line_items, dependent: :destroy

  def calculated_total
    line_items.sum { |item| item.quantity * item.unit_price}
  end
  
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_path, notice: "Customer was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.expect(customer: [ :name, :email ])
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy!

    respond_to do |format|
      format.html { redirect_to invoices_path, notice: "Invoice was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.expect(invoice: [ :customer_id, :due_date, :total_amount, :status ])
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_path, notice: "Line item was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.expect(line_item: [ :invoice_id, :description, :quantity, :unit_price ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <div>
    <strong>Name:</strong>
    <%= customer.name %>
  </div>

  <div>
    <strong>Email:</strong>
    <%= customer.email %>
  </div>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<% content_for :title, "Editing customer" %>

<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Customers" %>

<h1>Customers</h1>

<div id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer %>
    </p>
  <% end %>
</div>

<%= link_to "New customer", new_customer_path %>

app/views/customers/new.html.erb
<% content_for :title, "New customer" %>

<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div>
  <%= link_to "Edit this customer", edit_customer_path(@customer) %> |
  <%= link_to "Back to customers", customers_path %>

  <%= button_to "Destroy this customer", @customer, method: :delete %>
</div>

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_id, "Cliente" %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, { prompt: "Selecione um Cliente" } %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :total_amount, style: "display: block" %>
    <%= form.text_field :total_amount %>
  </div>

  <div>
    <%= form.label :status, "Status" %>
    <%= form.select :status, 
                    [
                      ['Rascunho', 'draft'], 
                      ['Enviada', 'sent'], 
                      ['Paga', 'paid']
                    ], 
                    { prompt: 'Selecione um status' } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">
  <div>
    <strong>Customer:</strong>
    <%= invoice.customer_id %>
  </div>

  <div>
    <strong>Due date:</strong>
    <%= invoice.due_date %>
  </div>

  <p>
    <strong>Total da Fatura:</strong>
    <%= number_to_currency(@invoice.calculated_total) %>
  </p>

  <div>
    <strong>Status:</strong>
    <%= invoice.status %>
  </div>

</div>

app/views/invoices/edit.html.erb
<% content_for :title, "Editing invoice" %>

<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Invoices" %>

<h1>Invoices</h1>

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
    <p>
      <%= link_to "Show this invoice", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<% content_for :title, "New invoice" %>

<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<table class="invoice-items-table">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Quantidade</th>
      <th>Preço Unitário</th>
      <th>Total do Item</th>
    </tr>
  </thead>
  <tbody>
    <% @invoice.line_items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.unit_price) %></td>
        <td><%= number_to_currency(item.quantity * item.unit_price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> |
  <%= link_to "Back to invoices", invoices_path %>

  <%= button_to "Destroy this invoice", @invoice, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meu App Faturas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Meu App Faturas">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :invoice_id, "Fatura" %>
    <%= form.collection_select :invoice_id, Invoice.all, :id, :id, { prompt: "Selecione uma Fatura" } %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :unit_price, style: "display: block" %>
    <%= form.text_field :unit_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <div>
    <strong>Invoice:</strong>
    <%= line_item.invoice_id %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= line_item.description %>
  </div>

  <div>
    <strong>Quantity:</strong>
    <%= line_item.quantity %>
  </div>

  <div>
    <strong>Unit price:</strong>
    <%= line_item.unit_price %>
  </div>

</div>

app/views/line_items/edit.html.erb
<% content_for :title, "Editing line item" %>

<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Line items" %>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<% content_for :title, "New line item" %>

<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>